name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 1.1.5
homepage: https://github.com/justkawal/excel

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.0.0-nullsafety.0
  xml: ^5.0.0-nullsafety.1
  process: ^4.0.0-nullsafety

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.10.0-nullsafety
